insert into Uyeler (uye_adi,uye_soyadi,cinsiyet,adres_no,telefon,e_posta) values ('Ayþe','Yýlmaz','kadýn',6,5321478569,'ayse.yilmaz@hotmail.com')
insert into Uyeler (uye_adi,uye_soyadi,cinsiyet,adres_no,telefon,e_posta) values ('Mehmet','Öztürk','erkek',1,5446912783,'mehmet.ozturk@hotmail.com')
insert into Uyeler (uye_adi,uye_soyadi,cinsiyet,adres_no,telefon,e_posta) values ('Zeynep','Kaya','kadýn',3,5027364821,'zeynep.kaya@outlook.com')
insert into Uyeler (uye_adi,uye_soyadi,cinsiyet,adres_no,telefon,e_posta) values ('Ahmet','Demir','erkek',7,5562309481,'ahmet.demir@outlook.com')
insert into Uyeler (uye_adi,uye_soyadi,cinsiyet,adres_no,telefon,e_posta) values ('Esra','Þahin','kadýn',1,5286734915,'esra.sahin@hotmail.com')
insert into Uyeler (uye_adi,uye_soyadi,cinsiyet,adres_no,telefon,e_posta) values ('Ali','Aksoy','erkek',2,5198243657,'ali.aksoy@gmail.com')
insert into Uyeler (uye_adi,uye_soyadi,cinsiyet,adres_no,telefon,e_posta) values ('Fatma','Yýldýz','kadýn',7,5349671028,'fatma.yildiz@hotmail.com')
insert into Uyeler (uye_adi,uye_soyadi,cinsiyet,adres_no,telefon,e_posta) values ('Ýbrahim','Arslan','erkek',0,5617439280,'ibrahim.arslan@gmail.com')
insert into Uyeler (uye_adi,uye_soyadi,cinsiyet,adres_no,telefon,e_posta) values ('Derya','Çelik','kadýn',0,5774628903,'derya.celik@hotmail.com')
insert into Uyeler (uye_adi,uye_soyadi,cinsiyet,adres_no,telefon,e_posta) values ('Hasan','Aydýn','erkek',1,5942137506,'hasan.aydin@hotmail.com')
insert into Uyeler (uye_adi,uye_soyadi,cinsiyet,adres_no,telefon,e_posta) values ('Ayþegül','Gündüz','kadýn',2,5663291847,'aysegul.gunduz@outlook.com')
insert into Uyeler (uye_adi,uye_soyadi,cinsiyet,adres_no,telefon,e_posta) values ('Mustafa','Kocaman','erkek',8,5812739546,'mustafa.kocaman@hotmail.com')
insert into Uyeler (uye_adi,uye_soyadi,cinsiyet,adres_no,telefon,e_posta) values ('Elif','Avcý','kadýn',4,5489267130,'elif.avci@outlook.com')
insert into Uyeler (uye_adi,uye_soyadi,cinsiyet,adres_no,telefon,e_posta) values ('Yusuf','Özdemir','erkek',9,5326174098,'yusuf.ozdemir@gmail.com')
insert into Uyeler (uye_adi,uye_soyadi,cinsiyet,adres_no,telefon,e_posta) values ('Seda','Özkan','kadýn',5,5631409872,'seda.ozkan@gmail.com')

