insert into Yazarlar (yazar_adi, yazar_soyadi) values('Deniz','Yýlmaz')
insert into Yazarlar (yazar_adi, yazar_soyadi) values('Ayþe','Kaya')
insert into Yazarlar (yazar_adi, yazar_soyadi) values('Mehmet','Öztürk')
insert into Yazarlar (yazar_adi, yazar_soyadi) values('Elif','Çelik')
insert into Yazarlar (yazar_adi, yazar_soyadi) values('Ali','Arslan')
insert into Yazarlar (yazar_adi, yazar_soyadi) values('Zeynep','Demir')
insert into Yazarlar (yazar_adi, yazar_soyadi) values('Yakup Kadri', 'Karaosmanoðlu')
insert into Yazarlar (yazar_adi, yazar_soyadi) values('Stephen', 'Hawking')
insert into Yazarlar (yazar_adi, yazar_soyadi) values('Ahmet','Þahin')
insert into Yazarlar (yazar_adi, yazar_soyadi) values('J.K.','Rowling')
insert into Yazarlar (yazar_adi, yazar_soyadi) values('J.R.R.','Tolkien')
insert into Yazarlar (yazar_adi, yazar_soyadi) values('Lev Mikolayeviç','Tolstoy')
